<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Akshay" failures="1" tests="6" name="com.TutorialNinja.TestCases.LoginTest" time="34.845" errors="0" timestamp="2024-07-16T21:14:32 IST" skipped="0">
  <testcase classname="com.TutorialNinja.TestCases.LoginTest" name="varifyLoginWithValidCerdentils" time="5.798"/>
  <testcase classname="com.TutorialNinja.TestCases.LoginTest" name="varifyLoginWithValidCerdentils" time="7.501"/>
  <testcase classname="com.TutorialNinja.TestCases.LoginTest" name="varifyLoginWithInvalidCredentils" time="6.865"/>
  <testcase classname="com.TutorialNinja.TestCases.LoginTest" name="varifyLoginWithInvalidEmailAndValidPasswordCredentils" time="3.999"/>
  <testcase classname="com.TutorialNinja.TestCases.LoginTest" name="varifyLoginWithValidEmailAndInValidPasswordCredentils" time="5.991"/>
  <testcase classname="com.TutorialNinja.TestCases.LoginTest" name="varifyLoginWithoutProvidingAnyCredentils" time="4.691">
    <failure message="Warning Message is not shown expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Warning Message is not shown expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.TutorialNinja.TestCases.LoginTest.varifyLoginWithoutProvidingAnyCredentils(LoginTest.java:84)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- varifyLoginWithoutProvidingAnyCredentils -->
</testsuite> <!-- com.TutorialNinja.TestCases.LoginTest -->
